# Generated by Django 5.1.7 on 2025-03-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('users', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Hackathon',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('full_description', models.TextField()),
                ('short_description', models.TextField()),
                ('image', models.ImageField(upload_to='hackathons/')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('registration_deadline', models.DateTimeField()),
                ('max_participants', models.PositiveIntegerField(default=100)),
                ('prize_pool', models.CharField(max_length=100)),
                ('location', models.CharField(max_length=200)),
                ('is_online', models.BooleanField(default=True)),
                ('tags', models.JSONField(default=list)),
                ('requirements', models.TextField()),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('participants', models.ManyToManyField(blank=True, related_name='hackathons', to='users.user')),
            ],
            options={
                'ordering': ['-start_date'],
            },
        ),
    ]
