# Generated by Django 5.1.7 on 2025-03-12 11:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tag',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='hackathon',
            name='tags',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='tags',
            field=models.ManyToManyField(blank=True, related_name='hackathons', to='hackathon.tag'),
        ),
    ]
