# Generated by Django 5.1.7 on 2025-03-14 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0002_alter_hackathon_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='hackathon',
            name='description',
        ),
        migrations.AddField(
            model_name='hackathon',
            name='full_description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hackathon',
            name='short_description',
            field=models.TextField(blank=True, null=True),
        ),
    ]
