# Generated by Django 5.1.7 on 2025-03-14 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_tag_created_at'),
        ('users', '0006_remove_userprofile_participated_hackathons_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='created_at',
        ),
        migrations.AlterField(
            model_name='hackathon',
            name='participants',
            field=models.ManyToManyField(related_name='participated_hackathons', to='users.userprofile'),
        ),
    ]
