# Generated by Django 5.1.7 on 2025-03-12 11:22

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_id', models.BigIntegerField(blank=True, null=True, unique=True)),
                ('name', models.CharField(max_length=100)),
                ('coin', models.IntegerField(default=0)),
                ('xp', models.IntegerField(default=0)),
                ('level', models.IntegerField(default=1)),
                ('avatar', models.ImageField(blank=True, null=True, upload_to='avatars/')),
                ('is_premium', models.BooleanField(default=False)),
                ('theme', models.CharField(choices=[('light', 'Светлая'), ('dark', 'Темная')], default='light', max_length=10)),
                ('language', models.CharField(choices=[('ru', 'Русский'), ('en', 'Английский')], default='ru', max_length=2)),
                ('email', models.EmailField(blank=True, max_length=254, null=True)),
                ('friends', models.ManyToManyField(blank=True, to='users.user')),
            ],
            options={
                'verbose_name': 'User',
                'verbose_name_plural': 'Users',
            },
        ),
    ]
