# Generated by Django 5.1.7 on 2025-03-14 14:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hackathon', '0004_tag_created_at'),
        ('users', '0003_techstack_userprofile_crystals_userprofile_friends_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='participated_hackathons',
            field=models.ManyToManyField(blank=True, related_name='all_participants', to='hackathon.hackathon'),
        ),
    ]
