# Generated by Django 5.1.7 on 2025-03-14 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_userprofile_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='participated_hackathons',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='user',
        ),
    ]
